script:
  - set -o pipefail && xcodebuild test -project KeyboardAdjuster.xcodeproj -scheme TestApplication -destination 'platform=iOS Simulator,name=iPhone X' | bundle exec xcpretty
  - bundle exec pod lib lint

before_install:
  - gem update --system
  - gem install bundler

language: objective-c
osx_image: xcode9.2
